# Form implementation generated from reading ui file 'C:\hxzhang\sourcecode\python\MagicTools\selectnamedlg.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SelectNameDialog(object):
    def setupUi(self, SelectNameDialog):
        SelectNameDialog.setObjectName("SelectNameDialog")
        SelectNameDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(SelectNameDialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tableView = QtWidgets.QTableView(SelectNameDialog)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 281, 301))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(SelectNameDialog)
        self.buttonBox.accepted.connect(SelectNameDialog.accept)
        self.buttonBox.rejected.connect(SelectNameDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SelectNameDialog)

    def retranslateUi(self, SelectNameDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectNameDialog.setWindowTitle(_translate("SelectNameDialog", "Dialog"))
